# Generated by Django 3.2.7 on 2021-10-14 14:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.PositiveSmallIntegerField(blank=True, choices=[('1', 'ریاضی'), ('2', 'تجربی'), ('3', 'انسانی'), ('4', 'هنر'), ('5', 'زبان')], null=True)),
                ('yob', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1400)])),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_student', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
