name: yaad_app
description: Yaad App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+10003

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  get: ^4.3.8
  get_storage: ^2.0.3
  timeago: ^3.1.0
  cached_network_image: ^3.1.0
  font_awesome_flutter: ^9.1.0
  flutter_rating_bar: ^4.0.0
  flutter_sticky_header: ^0.6.0
  url_launcher: ^6.0.12
  flutter_html: ^2.1.5
  focused_menu: ^1.0.5
  just_audio: ^0.9.12
  chewie: ^1.2.2
  video_player: ^2.2.5
  expandable: ^5.0.1
  pin_code_fields: ^7.3.0
  lottie: ^1.2.1
  toggle_switch: ^1.2.0
  objectbox: ^1.3.0
  objectbox_flutter_libs: ^1.3.0
  percent_indicator: ^3.4.0
  share: ^2.0.4
  in_app_review: ^2.0.3
  in_app_update: ^2.0.0
  firebase_core: ^1.10.5
  firebase_analytics: ^9.0.3
  firebase_messaging: ^11.2.3
  firebase_crashlytics: ^2.4.3
  appmetrica_sdk: ^0.0.7+1
  flutter_inappwebview: ^5.3.2
  showcaseview: ^1.1.3
  workmanager: ^0.4.1
  flutter_local_notifications: ^9.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  lint: ^1.5.3
  flutter_native_splash: ^1.3.2
  build_runner: ^2.1.4
  flutter_launcher_icons: ^0.9.2
  objectbox_generator: any
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/other/
    - assets/ca/

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Thin.ttf
          weight: 200
        - asset: assets/fonts/Vazir-Light.ttf
          weight: 300
        - asset: assets/fonts/Vazir-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazir-Bold.ttf
          weight: 600
        - asset: assets/fonts/Vazir-Black.ttf
          weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app-icon.png