# Generated by Django 3.2.7 on 2021-11-15 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_media_meta'),
        ('yaad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSlide',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('row', models.PositiveSmallIntegerField(default=0)),
                ('createdAt', models.DateTimeField(blank=True, editable=False)),
                ('updatedAt', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.media')),
            ],
            options={
                'verbose_name': 'historical slide',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStoreRow',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('show_title', models.BooleanField(default=False)),
                ('items', models.JSONField(default=list)),
                ('item_type', models.CharField(choices=[('S', 'slide'), ('B', 'book')], default='B', max_length=1)),
                ('row', models.PositiveSmallIntegerField(default=0)),
                ('createdAt', models.DateTimeField(blank=True, editable=False)),
                ('updatedAt', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical store row',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('row', models.PositiveSmallIntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yaad_banner_media_set', to='app.media')),
            ],
        ),
        migrations.CreateModel(
            name='StoreRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('show_title', models.BooleanField(default=False)),
                ('items', models.JSONField(default=dict)),
                ('item_type', models.CharField(choices=[('S', 'slide'), ('B', 'book')], default='B', max_length=1)),
                ('row', models.PositiveSmallIntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userbooks',
            name='book',
        ),
        migrations.RemoveField(
            model_name='userbooks',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='book',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercommentflag',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='usercommentflag',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userrates',
            name='book',
        ),
        migrations.RemoveField(
            model_name='userrates',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.DeleteModel(
            name='UserBooks',
        ),
        migrations.DeleteModel(
            name='UserComment',
        ),
        migrations.DeleteModel(
            name='UserCommentFlag',
        ),
        migrations.DeleteModel(
            name='UserRates',
        ),
    ]
