# Generated by Django 3.2.7 on 2021-11-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_lesson_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='course',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='book',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='book',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='book',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='media',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='section',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='question',
            name='book',
        ),
        migrations.RemoveField(
            model_name='question',
            name='media',
        ),
        migrations.RemoveField(
            model_name='question',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='chapter',
        ),
    ]
