# Generated by Django 3.2.5 on 2021-09-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatokhal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='book',
            name='video',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='video',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
