# Generated by Django 3.2.7 on 2021-09-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatokhal', '0002_auto_20210927_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, db_index=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='author',
            field=models.CharField(blank=True, db_index=True, default='', max_length=2048),
        ),
    ]
