# Generated by Django 3.2.7 on 2021-10-02 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import khatokhal.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('khatokhal', '0003_auto_20210928_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(max_length=4096, validators=[khatokhal.models.validate_media]),
        ),
        migrations.AlterField(
            model_name='book',
            name='video',
            field=models.CharField(blank=True, max_length=4096, null=True, validators=[khatokhal.models.validate_media]),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='image',
            field=models.CharField(max_length=4096, validators=[khatokhal.models.validate_media]),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='video',
            field=models.CharField(blank=True, max_length=4096, null=True, validators=[khatokhal.models.validate_media]),
        ),
        migrations.AlterField(
            model_name='historicallesson',
            name='media',
            field=models.CharField(blank=True, max_length=4096, null=True, validators=[khatokhal.models.validate_media]),
        ),
        migrations.AlterField(
            model_name='historicalquestion',
            name='media',
            field=models.CharField(blank=True, max_length=4096, null=True, validators=[khatokhal.models.validate_media]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='media',
            field=models.CharField(blank=True, max_length=4096, null=True, validators=[khatokhal.models.validate_media]),
        ),
        migrations.AlterField(
            model_name='question',
            name='media',
            field=models.CharField(blank=True, max_length=4096, null=True, validators=[khatokhal.models.validate_media]),
        ),
        migrations.CreateModel(
            name='StoreSlideRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('show_title', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('slides', models.ManyToManyField(to='khatokhal.Slide')),
            ],
        ),
        migrations.CreateModel(
            name='StoreRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField()),
                ('row', models.PositiveSmallIntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'khatokhal'), ('model', 'storebookrow')), models.Q(('app_label', 'khatokhal'), ('model', 'storesliderow')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='StoreBookRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('show_title', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('books', models.ManyToManyField(to='khatokhal.Book')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='khatokhal.course')),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='khatokhal.niveau')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='khatokhal.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalStoreSlideRow',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('show_title', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(blank=True, editable=False)),
                ('updatedAt', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical store slide row',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStoreRow',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField()),
                ('row', models.PositiveSmallIntegerField(default=0)),
                ('createdAt', models.DateTimeField(blank=True, editable=False)),
                ('updatedAt', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to=models.Q(models.Q(('app_label', 'khatokhal'), ('model', 'storebookrow')), models.Q(('app_label', 'khatokhal'), ('model', 'storesliderow')), _connector='OR'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical store row',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStoreBookRow',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('show_title', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(blank=True, editable=False)),
                ('updatedAt', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='khatokhal.course')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('niveau', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='khatokhal.niveau')),
                ('publisher', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='khatokhal.publisher')),
            ],
            options={
                'verbose_name': 'historical store book row',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
