# Generated by Django 3.2.7 on 2021-10-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatokhal', '0006_auto_20211013_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercomment',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='book',
            name='purchase_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='purchase_count',
            field=models.IntegerField(default=0),
        ),
    ]
