# Generated by Django 3.2.7 on 2021-11-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatokhal', '0009_auto_20211028_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercomment',
            options={'ordering': ('-pk',)},
        ),
        migrations.AddField(
            model_name='book',
            name='is_yaad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='is_yaad',
            field=models.BooleanField(default=False),
        ),
    ]
