# Generated by Django 3.2.7 on 2021-10-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
